name: DebugBuild

on:
  push:
    branches:
      - master

env:
  # リポジトリのルートディレクトリを起点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: ${{ github.workspace }}/CG2_0_1.sln
  # Visual Studio の構成
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: msbuild ${{ github.workspace }}/CG2_0_1.sln /p:Platform=x64 /p:Configuration=${{ env.CONFIGURATION }} /verbosity:detailed |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64 /p:Configuration=${{ env.CONFIGURATION }
